###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    mailhog:
      image: mailhog/mailhog:latest
      container_name: login-module-mailhog
      ports:
        - "8001:8025"

    redis:
      image: redis:alpine
      container_name: login-module-redis

    mysql:
      image: mysql:5.6
      container_name: login-module-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=buddy
        - MYSQL_DATABASE=login_module
        #- MYSQL_USER=root
        #- MYSQL_PASSWORD=buddy
      ports:
        - "8002:3306"

    webserver:
      image: nginx:alpine
      container_name: login-module-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: docker/php-fpm
      container_name: login-module-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini

